runtime: python37
entrypoint: gunicorn -b :$PORT main:app

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: auto

instance_class: F2

automatic_scaling:
  max_instances: 1
  min_instances: 0